resolution_2560x1920:
  video_mode: 5MP
  frame_rate: 12
resolution_2048x1536:
  video_mode: 3MP
  frame_rate: 20
resolution_1920x1080:
  video_mode: 2MP
  frame_rate: 30
resolution_1280x720:
  video_mode: 1MP
  frame_rate: 30
resolution_800x600:
  video_mode: SVGA
  frame_rate: 30
resolution_640x480:
  video_mode: VGA
  frame_rate: 30
video_format:
   default: h264
   list: [h264,mjpeg]
